# Type of algorithm globals
CLASSICS = "classics"
SELECTION = "selection"
OTRO = "otro"

# GUI values globals
CLEAR_TEXT_INPUT_BOX = "-CLEAR-TEXT-INPUT-BOX"
ENCRYPTED_TEXT_INPUT_BOX = "-ENCRYPTED-TEXT-INPUT-BOX-"
KEY_INPUT = "-KEY-INPUT-BOX-"

# Shift algorithm globals
ENCRYPT_SHIFT = "-ENCRYPT-SHIFT-"
DECRYPT_SHIFT = "-DECRYPT-SHIFT-"
GENERATE_SHIFT = "-GENERATE-SHIFT-"
ANALYZE_SHIFT = "-ANALYZE-SHIFT-"
